[package]
name = "adventure_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[example]]
name = "adventure-game"

[dependencies]
hecs = "0.9"
